services:  
  EasyProxy:
    build: https://github.com/nzo66/easyproxy.git#main
    container_name: easyproxy
    restart: unless-stopped
    ports:
      - '7860:7860'
    environment:
      - API_PASSWORD=ep
